# Generated by Django 3.2.3 on 2021-06-13 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210613_1356'),
        ('spares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars.car'),
        ),
    ]
