# Generated by Django 3.2.3 on 2021-07-01 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0007_alter_order_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spares.sale'),
        ),
    ]
