# Generated by Django 3.2.3 on 2021-07-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0015_auto_20210704_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='sales_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
