# Generated by Django 3.2.5 on 2021-07-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0018_auto_20210708_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='month',
            field=models.DateField(blank=True, null=True),
        ),
    ]
