# Generated by Django 3.2.3 on 2021-06-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartype',
            name='car',
        ),
        migrations.AddField(
            model_name='car',
            name='car_model',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
