# Generated by Django 3.2.3 on 2021-06-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spares', '0002_alter_item_car'),
        ('cars', '0002_auto_20210613_1356'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarType',
        ),
    ]
